[package]
name = "streamlined_ntru_prime"
version = "0.1.0"
authors = ["MitchellBerry <mitchellberry@protonmail.com>"]

[dependencies]
rand = "0.5.5"
sha2 = "0.8.0"
hex = "0.3.2"
serde = {version = "1.0.80", optional = true}
serde_json = {version = "1.0.32", optional = true}
serde_derive = {version = "1.0.80", optional = true}

[features]
default = []
tests = ["serde", "serde_json", "serde_derive"]