[package]
name = "ntru"
version = "0.1.0"
authors = ["MitchellBerry <mitchellberry@protonmail.com>"]


[dependencies]
rand = "0.5.5"
sha2 = "0.8.0"
hex = "0.3.2"
serde_json = "1.0.32"
serde = "1.0.80"
serde_derive = "1.0.80"